cmake_minimum_required(VERSION 3.15)
project(lecorder_kiwi LANGUAGES C CXX)
set(CMAKE_CXX_STANDARD 17)
foreach(option DYNAMIC CLI EVALUATOR MODEL_BUILDER TEST)
  set(KIWI_BUILD_${option} OFF CACHE BOOL "" FORCE)
endforeach()
add_subdirectory("${KIWI_SOURCE}" kiwi)
add_executable(kiwi-helper main.cpp)
target_include_directories(kiwi-helper PRIVATE "${KIWI_SOURCE}/include" "${KIWI_SOURCE}/third_party/json/single_include")
target_link_libraries(kiwi-helper PRIVATE kiwi_static)
